# Generated by Django 3.0.6 on 2020-10-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0003_auto_20201019_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.Districts')),
            ],
        ),
    ]
