# Generated by Django 3.0.6 on 2020-10-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_districts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microdistricts',
            name='district',
        ),
    ]
