# Generated by Django 3.0.6 on 2020-11-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_districts', '0002_remove_microdistricts_district'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='microdistricts',
            table='micro_district',
        ),
    ]
