# Generated by Django 3.0.6 on 2020-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
