# Generated by Django 3.0.6 on 2020-05-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200510_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
