# Generated by Django 3.0.6 on 2020-05-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_property'),
        ('listings', '0003_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
