# Generated by Django 3.0.6 on 2020-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_property'),
        ('listings', '0004_listing_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='property',
        ),
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ManyToManyField(null=True, to='images.Image'),
        ),
    ]
