# Generated by Django 3.0.6 on 2020-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_property'),
        ('listings', '0005_auto_20200511_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='property',
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
