# Generated by Django 3.0.6 on 2020-05-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200511_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Total area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchen_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='living_area',
            field=models.IntegerField(null=True),
        ),
    ]
