# Generated by Django 3.0.6 on 2020-05-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200516_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Total area',
            new_name='total_area',
        ),
    ]
