# Generated by Django 3.0.6 on 2020-05-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_types', '0001_initial'),
        ('listings', '0009_auto_20200516_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_types.HouseType'),
        ),
    ]
