# Generated by Django 3.0.6 on 2020-05-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
