# Generated by Django 3.0.6 on 2020-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20200523_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
