# Generated by Django 3.0.6 on 2020-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20200523_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='publisher_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
