# Generated by Django 3.0.6 on 2020-10-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_auto_20201019_2043'),
        ('listings', '0019_listing_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='districts.Districts'),
        ),
    ]
