# Generated by Django 3.0.6 on 2020-10-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_auto_20201023_1457'),
        ('listings', '0020_listing_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layout.Layout'),
        ),
    ]
