# Generated by Django 3.0.6 on 2020-11-20 16:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20201023_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
