# Generated by Django 3.0.6 on 2020-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
