# Generated by Django 3.0.6 on 2020-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20201125_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='source_publication_date',
            field=models.DateField(null=True),
        ),
    ]
