# Generated by Django 3.0.6 on 2020-11-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_listing_source_publication_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='listing',
        ),
    ]
