# Generated by Django 3.0.6 on 2020-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20201125_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publication_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_publication_date',
            field=models.DateTimeField(null=True),
        ),
    ]
