# Generated by Django 3.0.6 on 2020-11-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heating_type', '0001_initial'),
        ('listings', '0027_auto_20201125_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='type',
            new_name='house_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='heating_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heating_type.HeatingType'),
        ),
    ]
