# Generated by Django 3.0.6 on 2020-12-02 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_condition', '0001_initial'),
        ('listings', '0029_auto_20201202_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apartment_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment_condition.ApartmentCondition'),
        ),
    ]
