# Generated by Django 3.0.6 on 2020-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_listing_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
