# Generated by Django 3.0.6 on 2021-11-09 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0035_listing_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='listing_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
