# Generated by Django 3.0.6 on 2021-11-09 15:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_auto_20211109_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
