# Generated by Django 3.0.6 on 2020-10-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='type',
            new_name='country',
        ),
    ]
