# Generated by Django 3.0.6 on 2020-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_districts', '0002_remove_microdistricts_district'),
        ('districts', '0003_auto_20201019_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='micro_districts',
            field=models.ManyToManyField(to='micro_districts.MicroDistricts'),
        ),
    ]
