# Generated by Django 3.0.6 on 2020-11-22 16:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0004_districts_micro_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
