# Generated by Django 3.0.6 on 2020-11-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0005_districts_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='districts',
            table='district',
        ),
    ]
