# Generated by Django 3.0.6 on 2020-11-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0007_auto_20201129_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='name_uk',
        ),
    ]
