# Generated by Django 3.0.6 on 2020-11-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0008_auto_20201129_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='name',
        ),
    ]
