# Generated by Django 3.0.6 on 2020-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0009_remove_districts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
