# Generated by Django 3.0.6 on 2020-11-29 12:16

from django.db import migrations
import localized_fields.fields.field


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0012_auto_20201129_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='name',
            field=localized_fields.fields.field.LocalizedField(max_length=250, null=True, required=[]),
        ),
    ]
