# Generated by Django 3.0.6 on 2020-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0013_auto_20201129_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
