# Generated by Django 3.0.6 on 2020-12-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heating_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heatingtype',
            old_name='name',
            new_name='title',
        ),
    ]
