# Generated by Django 3.0.6 on 2020-11-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='streets',
            table='street',
        ),
    ]
