# Generated by Django 3.0.6 on 2021-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('news', '0007_auto_20210102_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='news_comment', to='comments.Comment'),
        ),
    ]
