# Generated by Django 3.0.6 on 2021-01-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggs', '0001_initial'),
        ('news', '0008_news_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='news_tags', to='taggs.Tag'),
        ),
    ]
