# Generated by Django 3.0.6 on 2020-05-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='property',
        ),
    ]
