# Generated by Django 3.0.6 on 2020-06-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200516_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(max_length=300, null=True, upload_to='photos'),
        ),
    ]
