# Generated by Django 3.0.6 on 2020-11-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_dropbox__'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
