# Generated by Django 3.0.6 on 2020-12-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_types', '0002_auto_20201125_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housetype',
            old_name='type',
            new_name='title',
        ),
    ]
