# Generated by Django 3.0.6 on 2020-12-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bathroomtype',
            old_name='type',
            new_name='title',
        ),
    ]
