# Generated by Django 3.0.6 on 2020-10-23 14:57

from django.db import migrations


# [Providing initial data for models | Django documentation | Django](
# https://docs.djangoproject.com/en/3.1/howto/initial-data/) [Django insert default data after migrations - Stack
# Overflow](https://stackoverflow.com/questions/39739439/django-insert-default-data-after-migrations)


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Layout = apps.get_model("layout", "Layout")
    available_layouts = [
        'Смежная, проходная',
        'Раздельная',
        'Студия',
        'Пентхаус',
        'Многоуровневая',
        "Малосемейка, гостинка",
        'Смарт-квартира',
        'Свободная планировка',
        'Двухсторонняя'
    ]
    for layout in available_layouts:
        new_layout = Layout(name=layout)
        new_layout.save()


class Migration(migrations.Migration):
    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
