# Generated by Django 3.0.6 on 2020-11-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_auto_20201023_1457'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='layout',
            table='Layout',
        ),
    ]
