# Generated by Django 3.0.6 on 2020-11-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_auto_20201125_1710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='layout',
            table='layout',
        ),
    ]
