# Generated by Django 3.0.6 on 2020-12-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_auto_20201125_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='name',
            new_name='title',
        ),
    ]
